{% set name = "lb-nightly-functions" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb-nightly-functions-{{ version }}.tar.gz
  sha256: d32ee10d2cb4fba4a7cbe1a168ad1681dc41fb799a8585a5d83048328a6851aa

build:
  number: 0
  noarch: python
  entry_points:
    - lb-wrapcmd = lb.nightly.functions.common:lb_wrapcmd
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - archspec >=0.1.2,<0.2.0
    - gitpython >=3.1.18,<4.0.0
    - lb-nightly-configuration >=0.3,<1.0
    - lb-nightly-db >=0.2,<1.0
    - lb-nightly-utils >=0.4,<1.0
    - lbplatformutils >=4.3.8,<5.0.0
    - python >=3.6,<4.0
    - python-gitlab >=3.9.0,<4.0.0

test:
  imports:
    - lb
    - lb.nightly.functions
  commands:
    - pip check
    - lb-wrapcmd --help
  requires:
    - git
    - pip

about:
  home: https://pypi.org/project/lb-nightly-functions/
  summary: Core functions for LHCb Nightly and Continuous Integration Build System
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pikacic
    - maszyman
